col_names <- c("Cases","Control")
row_names <- c("Yes","No")
x <- matrix(c(688,21,650,59), ncol = 2)
dimnames(x) <- list( "Have Smoked" = row_names,"Lung Cancer" = col_names)
print(x)
print("H0: Suffering from lung cancer is indepedent from the previous smoking behaviour")
print("H1: Suffering from lung cancer is depedent on the previous smoking behaviour")
chisq <- chisq.test(x)
print(chisq)
fisher.test(x)
